FROM ubuntu:impish

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y build-essential ruby ruby-dev make libffi-dev devscripts
RUN gem install ruby-xz -v 0.2.3
RUN gem install fpm
RUN apt-get autoremove -y
RUN apt-get clean all
