FROM debian:8

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y build-essential ruby ruby-dev make libffi-dev devscripts
RUN gem install fpm --no-rdoc --no-ri
RUN apt-get autoremove -y
RUN apt-get clean all
